feat: use linea-goerli as testnet
layer-3/clearsync pull request #171
Opened 2024-01-18 09:54 UTC by philanton

2024-01-18 10:29 UTC, mnaichuk requested changes

2024-01-18 10:29 UTC, mnaichuk commented on networks/testnet/assets.json
> +      "name": "Duckies, the canary network for Yellow",
better simple Duckier or Duckies Yellow

2024-01-18 10:32 UTC, nksazonov approved these changes

2024-01-18 10:42 UTC, philanton commented on networks/testnet/assets.json
> +      "name": "Duckies, the canary network for Yellow",
https://github.com/layer-3/clearsync/pull/171/commits/6fe457954f0763b11b2507068b90ec2373694ec5

2024-01-18 12:25 UTC, mnaichuk commented on networks/testnet/markets.json
> +    "spot://LINDA/USDT"
there is not trading activity for this token 
https://coinmarketcap.com/dexscan/ethereum/0x246ba530d046c0ae454b5e962a9c4ede382047bd/

2024-01-18 12:29 UTC, mnaichuk commented on networks/testnet/markets.json
> +    "spot://LINDA/USDT"
<img width="401" alt="Screenshot 2024-01-18 at 13 28 02" src="https://github.com/layer-3/clearsync/assets/26766307/f77d8efa-71a0-4f5f-a2bb-5c0e7e3461e8">
<img width="391" alt="Screenshot 2024-01-18 at 13 29 06" src="https://github.com/layer-3/clearsync/assets/26766307/09601032-0277-4a7f-849a-9a2108a50cc4">

2024-01-22 08:24 UTC, dpatsora commented on networks/testnet/markets.json
> +    "spot://LUBE/USDT",
I suggest to remote Lube and Linda from this list, until we figure out where to pull the prices

2024-01-22 09:12 UTC, mnaichuk approved these changes

2024-01-22 09:56 UTC, merged