feat: use Market instead of Symbol in TradeEvent
layer-3/clearsync pull request #193
Opened 2024-02-02 15:54 UTC by MaxMoskalenko

2024-02-05 10:00 UTC, maxpushka requested changes

2024-02-05 10:12 UTC, MaxMoskalenko commented on pkg/quotes/market.go
> +}
It will be used in dependent packages (e.g. neodax, clearport)

2024-02-05 10:14 UTC, maxpushka commented on pkg/quotes/market.go
> +}
Yeah, just found it out after I looked into a PR for Neodax 😀

2024-02-05 10:35 UTC, maxpushka commented on pkg/quotes/market.go
> +}
That's right but it also depends on context. The current package design does not force clients to use the constructor, which could lead to inconsistency in how instances of the `Market` type are created throughout the codebase. To force this, getters can be added alongside making the fields private.

Direct struct initialization also has the advantage of making the code more idiomatic to Go, where the language's design encourages simplicity and direct manipulation of struct fields when possible.

2024-02-05 11:29 UTC, MaxMoskalenko commented on pkg/quotes/market.go
> +}
I change both fields to private scope, to prevent (lower/upper)case problems in the future

2024-02-06 13:20 UTC, maxpushka approved these changes

2024-02-06 13:20 UTC, merged