feat: solidity style guide
layer-3/clearsync pull request #428
Opened 2024-09-11 12:43 UTC by nksazonov

2024-09-12 13:09 UTC, maxpushka requested changes

2024-09-12 13:09 UTC, maxpushka commented on contracts/solidity-style-guide.md
> +Explicit naming parameters in mapping types is helpful for clarity, especially when nesting is used.
```suggestion
Explicitly naming parameters in mapping types is helpful for clarity, especially when nesting is used.
```

2024-09-23 11:59 UTC, nksazonov commented on contracts/solidity-style-guide.md
> +For example, `InsufficientBalance`.
7ab77dbd87c0e4f2eaeed3e9d85133c579066b06

2024-09-23 12:12 UTC, nksazonov commented on contracts/solidity-style-guide.md
> +```
7ab77dbd87c0e4f2eaeed3e9d85133c579066b06

2024-09-23 12:12 UTC, nksazonov commented on contracts/solidity-style-guide.md
> +```
7ab77dbd87c0e4f2eaeed3e9d85133c579066b06

2024-09-23 12:13 UTC, nksazonov commented on contracts/solidity-style-guide.md
> +While the main contracts we deploy should specify a single Solidity version, all supporting contracts and libraries should have as open a Pragma as possible. A good rule of thumb is to the next major
7ab77dbd87c0e4f2eaeed3e9d85133c579066b06

2024-09-23 12:13 UTC, nksazonov commented on contracts/solidity-style-guide.md
> +Note, we cannot remedy this by insisting on the use public functions. Whether a library functions are internal or external has important implications. From the [Solidity documentation](https://docs.s
7ab77dbd87c0e4f2eaeed3e9d85133c579066b06

2024-09-23 12:13 UTC, nksazonov commented on contracts/solidity-style-guide.md
> +Explicit naming parameters in mapping types is helpful for clarity, especially when nesting is used.
7ab77dbd87c0e4f2eaeed3e9d85133c579066b06

2024-09-23 12:16 UTC, nksazonov commented on contracts/solidity-style-guide.md
> +This style guide is a set of rules and conventions for writing Solidity code. It is based on the [Solidity Style Guide](https://docs.soliditylang.org/en/latest/style-guide.html), [Coinbase Style Guid
> Use rule structure similar to [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html):

In the most controversial and opinionated cases this structure is a great approach, whereas in general the simple definition or explanation should suffice.

Nevertheless, we can change this if we see the need to it.

2024-09-23 12:18 UTC, nksazonov commented on contracts/solidity-style-guide.md
> +This style guide is a set of rules and conventions for writing Solidity code. It is based on the [Solidity Style Guide](https://docs.soliditylang.org/en/latest/style-guide.html), [Coinbase Style Guid
> Add some common gas usage optimizations

Indeed, I had some thoughts of adding gas optimization technics to this document, however later realized that alongside the security technics, they should be outlined in a separate document.

The Style Guide declares the syntax and semantics of writing contracts, whereas gas optimizations and security technics are more complex terms.

Still, great thanks for reminding about this topic!

2024-09-23 14:40 UTC, nksazonov commented on contracts/solidity-style-guide.md
> +This style guide is a set of rules and conventions for writing Solidity code. It is based on the [Solidity Style Guide](https://docs.soliditylang.org/en/latest/style-guide.html), [Coinbase Style Guid
> Add some common gas usage optimizations

@maxpushka 
I have added a [Solidity Development Practices](https://github.com/layer-3/clearsync/blob/f7dedf31dc9858d59c44366423f542eb8e834829/contracts/solidity-development-practices.md) document to store optimizations and security technics there.

2024-09-29 10:41 UTC, dpatsora approved these changes
Nikita, thank you for such comprehensive guides!!

2024-09-30 07:47 UTC, merged