feat: copy contracts from layer-3/yellow
layer-3/clearsync pull request #54
Opened 2023-04-21 16:08 UTC by philanton

2023-04-24 13:14 UTC, nksazonov requested changes
Need to add solidity@0.8.17 to hardhat config.

2023-08-28 11:59 UTC, nksazonov commented on contracts/interfaces/IClearing.sol
> +    struct SwapCall {
SettlementRequest

2023-08-28 12:01 UTC, nksazonov commented on contracts/ClearingApp.sol
> +contract ClearingApp is IForceMoveApp {
TODO: think of a better name + versioning (...v1.sol)

2023-08-28 14:15 UTC, mod approved these changes

2023-08-28 14:16 UTC, merged